### ISSUE TITLE
Why not the default Rails 4 caching mechanism?

### ISSUE THREAD

**Issue by TangRufus** [zendesk/curly#154]
Is there any benefit to define `#cache_key` in `Presenter` over `.erb`?

**Comment by dasch** [comment]
This *is* the default caching mechanism – the syntax is simply different. In ERb, the view file (`foo.erb`) contains both the Ruby code _and_ HTML structure. The cache key is passed to the `cache` method. In Curly, the Ruby code is defined in the presenter while the HTML is kept in the view. When compiling a view, Curly automatically wraps it with a `cache` method call if the presenter defines a non-nil `cache_key` method.

As for whether there are any benefits: since the cache key is defined in a publicly accessible method, it's possible to test it directly, e.g.

```ruby
it "returns nil when the user is signed in" do
  user.stub(:signed_in?) { false }
  presenter.cache_key.should be_nil
end

...
```
